# Generated by Django 6.0.7 on 2026-07-14 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['nombre'], 'verbose_name': 'Terminal', 'verbose_name_plural': 'Terminales'},
        ),
        migrations.RemoveField(
            model_name='bus',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='fecha_ultimo_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='terminal_actual',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='telefono',
        ),
        migrations.AddField(
            model_name='bus',
            name='accesibilidad_universal',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='id_bus',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='terminal',
            name='id_terminal',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='id_terminal',
            field=models.ForeignKey(blank=True, db_column='id_terminal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='terminales.terminal'),
        ),
        migrations.AddField(
            model_name='bus',
            name='kilometraje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='capacidad_buses',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bus',
            name='patente',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='bus',
            table='bus',
        ),
        migrations.AlterModelTable(
            name='terminal',
            table='terminal',
        ),
    ]
