# Generated by Django 6.0.7 on 2026-07-15 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminales', '0002_alter_terminal_options_remove_bus_anio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio_contrato', models.DateField()),
            ],
            options={
                'db_table': 'administrativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('num_asiento', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'asiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id_boleto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_compra', models.DateTimeField(auto_now_add=True)),
                ('tipo_boleto', models.CharField(max_length=20)),
                ('num_asiento', models.IntegerField()),
                ('ciudad_inicial', models.CharField(max_length=100)),
                ('ciudad_final', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'boleto',
                'ordering': ['-fecha_hora_compra'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusReporte',
            fields=[
                ('id_bus', models.ForeignKey(db_column='id_bus', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='terminales.bus')),
            ],
            options={
                'db_table': 'bus_reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id_chofer', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio_contrato', models.DateField()),
            ],
            options={
                'db_table': 'chofer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('pk', models.CompositePrimaryKey('ciudad_inicial', 'ciudad_final', blank=True, editable=False, primary_key=True, serialize=False)),
                ('ciudad_inicial', models.CharField(max_length=50)),
                ('ciudad_final', models.CharField(max_length=50)),
                ('descuento_estudiante', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('descuento_adulto_mayor', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'tramo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('id_chofer', models.IntegerField()),
            ],
            options={
                'db_table': 'viaje',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='bus',
            name='patente',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='ChoferReporte',
            fields=[
                ('id_reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='terminales.reporte')),
            ],
            options={
                'db_table': 'chofer_reporte',
                'managed': False,
            },
        ),
    ]
