# Generated by Django 6.0.6 on 2026-07-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminales', '0003_administrativo_asiento_boleto_busreporte_chofer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramoViaje',
            fields=[
                ('pk', models.CompositePrimaryKey('ciudad_inicial', 'ciudad_final', 'id_viaje', blank=True, editable=False, primary_key=True, serialize=False)),
                ('ciudad_inicial', models.CharField(max_length=50)),
                ('ciudad_final', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tramo_viaje',
                'managed': False,
            },
        ),
    ]
